Added control to postgres database

diff --git a/fs/mnt/hdd/BTCPAYSERVER/bin/doit b/fs/mnt/hdd/BTCPAYSERVER/bin/doit
--- a/fs/mnt/hdd/BTCPAYSERVER/bin/doit
+++ b/fs/mnt/hdd/BTCPAYSERVER/bin/doit
@@ -4,6 +4,8 @@
 
 BASEDIR=/mnt/hdd/BTCPAYSERVER
 
+QUERY=/mnt/hdd/BTCPAYSERVER/bin/psql_query
+
 if [ -f $BASEDIR/conf/payer.conf ]
 then
    . $BASEDIR/conf/payer.conf
@@ -20,6 +22,16 @@ fi
 
 amount=$2
 memo=$3
+oldInvoice=$4
+paymentId=$5
+
+if [ -z "$paymentId" ]
+then
+   echo you have to inform a payment Id
+   exit 1
+fi
+
+
 
 if [ -z "$amount" ]
 then
@@ -212,21 +224,33 @@ fi
 tokenPayer=$token
 #echo tokenPayer: $tokenPayer
 
-generate $hostStore $tokenStore $amount "$memo"
-
-if [ "$payment_request" = "null" ]
+if [ -z "$oldInvoice" ]
 then
-   echo "Could not get invoice... [$ret]"
-   exit 1
+   generate $hostStore $tokenStore $amount "$memo"
+
+   if [ "$payment_request" = "null" ]
+   then
+     echo "Could not get invoice... [$ret]"
+     exit 1
+   fi
+   echo generated invoice [$payment_request]
+   $QUERY "insert into invoices(id,dh,amount,invoice) values ('$paymentId','now',$amount, '$payment_request')" insert
+   #exit 1
+
+else
+   payment_request=$oldInvoice
 fi
 
 invoice=$payment_request
 
 pay $hostPayer $tokenPayer "$invoice"
+
 if [ "$error" = "true" ]
 then
   echo error while paying invoice: [$errmsg]
   exit 1
 fi
+
+   $QUERY "update invoices set paid=$amount where id='$paymentId' " update
 
 exit 0
